# Generated by Django 5.2.17 on 2026-10-05 06:46

import uuid

import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackupRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("database", "Database dump"),
                            ("media", "Media copy"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("run_date", models.DateField(default=django.utils.timezone.localdate)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "object_key",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("objects_copied", models.IntegerField(blank=True, null=True)),
                ("row_counts", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-started_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["database", "media"])),
                        name="backuprun_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["running", "succeeded", "failed", "skipped"],
                            )
                        ),
                        name="backuprun_status_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "succeeded")),
                        fields=("kind", "run_date"),
                        name="backuprun_one_success_per_day",
                    ),
                ],
            },
        ),
    ]
