# Generated by Django 5.2.17 on 2026-10-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops", "0002_db_guards"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="backuprun",
            name="backuprun_kind_valid",
        ),
        migrations.AlterField(
            model_name="backuprun",
            name="kind",
            field=models.CharField(
                choices=[
                    ("database", "Database dump"),
                    ("media", "Media copy"),
                    ("paper", "Paper backup"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="backuprun",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["database", "media", "paper"])),
                name="backuprun_kind_valid",
            ),
        ),
    ]
