# Generated by Django 5.2.17 on 2026-10-05 06:46

import uuid

import django.contrib.postgres.fields
import django.core.serializers.json
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                ("key", models.SlugField(max_length=60, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        help_text="Leave empty to enable for every role.",
                        size=None,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
                ("actor_role", models.CharField(blank=True, default="", max_length=20)),
                ("source", models.CharField(blank=True, default="", max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("soft_delete", "Deleted"),
                            ("restore", "Restored"),
                            ("login", "Signed in"),
                            ("login_failed", "Failed sign-in"),
                            ("logout", "Signed out"),
                            ("locked_out", "Account locked"),
                            ("password_change", "Password changed"),
                            ("2fa_enabled", "Two-factor enabled"),
                            ("2fa_disabled", "Two-factor removed"),
                            ("recovery_code_used", "Recovery code used"),
                        ],
                        max_length=30,
                    ),
                ),
                ("object_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "object_repr",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "before",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "after",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "changed_fields",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("request_id", models.CharField(blank=True, default="", max_length=64)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "-at"],
                        name="audit_object_idx",
                    ),
                    models.Index(fields=["actor", "-at"], name="audit_actor_idx"),
                    models.Index(fields=["action", "-at"], name="audit_action_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "action__in",
                                [
                                    "create",
                                    "update",
                                    "soft_delete",
                                    "restore",
                                    "login",
                                    "login_failed",
                                    "logout",
                                    "locked_out",
                                    "password_change",
                                    "2fa_enabled",
                                    "2fa_disabled",
                                    "recovery_code_used",
                                ],
                            )
                        ),
                        name="auditlog_action_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                ("read_only_mode", models.BooleanField(default=False)),
                (
                    "banner_message",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "banner_level",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("id", uuid.UUID("00000000-0000-0000-0000-000000000001"))
                        ),
                        name="sitesettings_singleton",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("banner_level__in", ["info", "warning", "critical"])),
                        name="sitesettings_banner_level_valid",
                    ),
                ],
            },
        ),
    ]
