# Generated by Django 5.2.17 on 2026-10-05 16:58

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0002_db_guards"),
        ("units", "0003_feature_flag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Work order numbers: WO-20001 upwards (old paper cards use 4 digits).
        migrations.RunSQL(
            "CREATE SEQUENCE IF NOT EXISTS service_work_order_number_seq START 20001",
            "DROP SEQUENCE IF EXISTS service_work_order_number_seq",
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("repair", "Repair"),
                            ("maintenance", "Planned maintenance"),
                            ("inspection", "Inspection"),
                            ("prep", "Prep for sale"),
                            ("warranty", "Warranty"),
                        ],
                        default="repair",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("on_hold", "On hold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("shop", "In the shop"), ("field", "On site (field)")],
                        default="shop",
                        max_length=10,
                    ),
                ),
                ("complaint", models.TextField(blank=True, default="")),
                ("cause", models.TextField(blank=True, default="")),
                ("correction", models.TextField(blank=True, default="")),
                (
                    "hold_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "customer_po",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("contact", models.CharField(blank=True, default="", max_length=120)),
                (
                    "opened_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("due_on", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="customers.customer",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hour_reading",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_order",
                        to="units.hourmeterreading",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="units.unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_on", "-number"],
            },
        ),
        migrations.CreateModel(
            name="LaborLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "work_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mechanic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor",
                        to="service.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["work_date", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["status", "-opened_on"], name="work_order_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["open", "in_progress", "on_hold", "completed", "cancelled"],
                    )
                ),
                name="work_order_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        ["repair", "maintenance", "inspection", "prep", "warranty"],
                    )
                ),
                name="work_order_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("location__in", ["shop", "field"])),
                name="work_order_location_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "completed"), _negated=True),
                    models.Q(
                        ("completed_at__isnull", False),
                        models.Q(("correction", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="work_order_completed_has_correction",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("due_on__isnull", True),
                    ("due_on__gte", models.F("opened_on")),
                    _connector="OR",
                ),
                name="work_order_due_after_opened",
            ),
        ),
        migrations.AddConstraint(
            model_name="laborline",
            constraint=models.CheckConstraint(
                condition=models.Q(("hours__gt", 0), ("hours__lte", 24)),
                name="labor_hours_sane",
            ),
        ),
    ]
