# Generated by Django 5.2.17 on 2026-10-05 17:22

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0003_feature_flag"),
        ("units", "0003_feature_flag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="plan_prev_done_hours",
            field=models.DecimalField(
                blank=True, decimal_places=1, editable=False, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="plan_prev_done_on",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="MaintenancePlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("tasks", models.TextField(blank=True, default="")),
                ("interval_hours", models.PositiveIntegerField(blank=True, null=True)),
                ("interval_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "last_done_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "last_done_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=9,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_plans",
                        to="units.unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="workorder",
            name="maintenance_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_orders",
                to="service.maintenanceplan",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenanceplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="plan_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenanceplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("interval_hours__gt", 0), ("interval_hours__isnull", False)),
                    models.Q(("interval_days__gt", 0), ("interval_days__isnull", False)),
                    _connector="OR",
                ),
                name="plan_has_an_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenanceplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("interval_hours__isnull", True),
                    ("last_done_hours__isnull", False),
                    _connector="OR",
                ),
                name="plan_hours_need_a_start",
            ),
        ),
    ]
