#!/usr/bin/env python3
"""Build the Droplet's /opt/mmh/.env from Terraform outputs and CI secrets.

Usage (in GitHub Actions):
    terraform output -json | python3 infra/scripts/build_env.py > app.env

Terraform supplies addresses, database URLs and Spaces keys; secrets that are
not in Terraform (Django secret key, Sentry DSN, Cloudflare token, ...) come
from environment variables. The output is sent over SSH on stdin and never
written to the CI log.
"""

from __future__ import annotations

import json
import os
import sys

REQUIRED_SECRETS = [
    "APP_ENV",
    "APP_VERSION",
    "APP_IMAGE_REPO",
    "CADDY_IMAGE",
    "DJANGO_SECRET_KEY",
    "CLOUDFLARE_API_TOKEN",
    "ACME_EMAIL",
    "BACKUP_AGE_RECIPIENT",
    "GHCR_USER",
    "GHCR_TOKEN",
]
OPTIONAL_SECRETS = ["SENTRY_DSN", "SENTRY_FRONTEND_DSN", "GUNICORN_WORKERS", "LOG_LEVEL"]


def quote(name: str, value: str) -> str:
    if "\n" in value or "'" in value:
        raise SystemExit(f"{name} contains a newline or single quote, which is not allowed")
    return f"{name}='{value}'"


def main() -> None:
    tf = {k: v["value"] for k, v in json.load(sys.stdin).items()}
    missing = [k for k in REQUIRED_SECRETS if not os.environ.get(k)]
    if missing:
        raise SystemExit(f"missing required settings: {', '.join(missing)}")
    env = os.environ
    host = tf["hostname"]
    pooled = tf["database_pooled_url"] + "?sslmode=require"
    direct = tf["database_direct_url"] + "?sslmode=require"
    values = {
        "APP_ENV": env["APP_ENV"],
        "APP_VERSION": env["APP_VERSION"],
        "APP_IMAGE_REPO": env["APP_IMAGE_REPO"],
        "CADDY_IMAGE": env["CADDY_IMAGE"],
        "SITE_DOMAIN": host,
        "ACME_EMAIL": env["ACME_EMAIL"],
        "CLOUDFLARE_API_TOKEN": env["CLOUDFLARE_API_TOKEN"],
        "GHCR_USER": env["GHCR_USER"],
        "GHCR_TOKEN": env["GHCR_TOKEN"],
        "DJANGO_SETTINGS_MODULE": "config.settings.prod",
        "DJANGO_SECRET_KEY": env["DJANGO_SECRET_KEY"],
        "DJANGO_ALLOWED_HOSTS": host,
        "DJANGO_CSRF_TRUSTED_ORIGINS": f"https://{host}",
        "DATABASE_URL": pooled,
        "DB_BEHIND_POOLER": "true",
        "DATABASE_DIRECT_URL": direct,
        "DATABASE_SSLMODE": "require",
        "DATABASE_SSLROOTCERT": "/certs/do-ca.crt",
        "BACKUP_DATABASE_URL": direct,
        "S3_ENDPOINT_URL": tf["media_endpoint"],
        "S3_REGION": tf["media_endpoint"].split("//")[1].split(".")[0],
        "S3_ACCESS_KEY_ID": tf["spaces_app_key_id"],
        "S3_SECRET_ACCESS_KEY": tf["spaces_app_key_secret"],
        "MEDIA_BUCKET": tf["media_bucket"],
        "BACKUP_BUCKET": tf["backup_bucket"],
        "BACKUP_S3_ENDPOINT_URL": tf["backup_endpoint"],
        "BACKUP_S3_REGION": tf["backup_endpoint"].split("//")[1].split(".")[0],
        "BACKUP_S3_ACCESS_KEY_ID": tf["spaces_app_key_id"],
        "BACKUP_S3_SECRET_ACCESS_KEY": tf["spaces_app_key_secret"],
        "BACKUP_AGE_RECIPIENT": env["BACKUP_AGE_RECIPIENT"],
        "CSP_IMG_SRC_EXTRA": tf["media_endpoint"].replace("https://", f"https://{tf['media_bucket']}."),
    }
    for name in OPTIONAL_SECRETS:
        if env.get(name):
            values[name] = env[name]
    # ADMIN_* lines are split off on the server into admin.env, which is only
    # read by the migrate step; app containers never see the owner password.
    values["ADMIN_DATABASE_URL"] = tf["database_admin_url"] + "?sslmode=require"
    values["APP_DB_ROLE"] = tf["database_app_role"]
    print("# Generated by the deploy workflow. Do not edit on the server.")
    for name, value in values.items():
        print(quote(name, str(value)))


if __name__ == "__main__":
    main()
