# Generated by Django 5.2.17 on 2026-10-05 06:46

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(blank=True, default="", max_length=80)),
                ("last_name", models.CharField(blank=True, default="", max_length=80)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("sales", "Sales"),
                            ("service", "Service"),
                            ("parts", "Parts"),
                            ("read_only", "Read only"),
                        ],
                        default="read_only",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["first_name", "last_name", "email"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        name="user_email_unique_ci",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "role__in",
                                ["admin", "sales", "service", "parts", "read_only"],
                            )
                        ),
                        name="user_role_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("email", ""), _negated=True),
                        name="user_email_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True),
                            ("is_active", False),
                            _connector="OR",
                        ),
                        name="user_deleted_is_inactive",
                    ),
                ],
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
    ]
