"""Files generated from columns.COLUMNS: the CSV template, the sample file, the
JSON Schema and docs/IMPORT_FORMAT.md."""

from __future__ import annotations

import csv
import io
import json
from typing import Any

from .columns import COLUMNS, MAX_ATTACHMENTS, SAMPLE_ROWS, Column

API_PATH = "/api/v1/import/v1/units"


def _csv(rows: list[dict[str, str]]) -> str:
    out = io.StringIO()
    writer = csv.writer(out, lineterminator="\r\n")
    writer.writerow([c.name for c in COLUMNS])
    for row in rows:
        writer.writerow([row.get(c.name, "") for c in COLUMNS])
    return out.getvalue()


def template_csv() -> str:
    """Header row only. Starts with a byte-order mark so Excel opens it as UTF-8."""
    return "﻿" + _csv([])


def sample_csv() -> str:
    return "﻿" + _csv(SAMPLE_ROWS)


def _schema_for(col: Column) -> dict[str, Any]:
    if col.kind == "bool":
        return {"type": ["boolean", "string"], "description": col.help}
    if col.kind in ("int", "decimal", "hours", "money"):
        out: dict[str, Any] = {"type": ["number", "string"], "description": col.help}
        if col.minimum is not None:
            out["minimum"] = col.minimum
        if col.maximum is not None:
            out["maximum"] = col.maximum
        return out
    if col.kind == "forks" or col.name == "source_image_filename":
        return {
            "oneOf": [{"type": "string"}, {"type": "array", "items": {"type": "string"}}],
            "description": col.help,
        }
    if col.kind == "choice":
        return {
            "type": "string",
            "enum": sorted(set(col.choices.values())),
            "description": col.help,
        }
    if col.kind == "date":
        return {"type": "string", "description": col.help, "examples": ["2024-03-12"]}
    out = {"type": "string", "description": col.help}
    if col.max_length:
        out["maxLength"] = col.max_length
    return out


def json_schema() -> dict[str, Any]:
    unit = {
        "type": "object",
        "description": "One unit card. Same keys as the CSV columns. Blank or missing values are left alone.",
        "properties": {c.name: _schema_for(c) for c in COLUMNS},
        "anyOf": [{"required": ["unit_serial"]}, {"required": ["stock_number"]}],
        "additionalProperties": False,
    }
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://dms.maine-material.com/api/v1/import/v1/schema.json",
        "title": "Maine Material Handling unit card import (v1)",
        "type": "object",
        "required": ["units"],
        "properties": {
            "units": {
                "type": "array",
                "minItems": 1,
                "maxItems": 1000,
                "items": {"$ref": "#/$defs/unit"},
            },
            "reference": {
                "type": "string",
                "maxLength": 100,
                "description": "Your own id for this batch.",
            },
            "dry_run": {
                "type": "boolean",
                "default": False,
                "description": "Check only; change nothing.",
            },
            "on_existing": {"type": "string", "enum": ["update", "skip"], "default": "update"},
            "skip_invalid": {
                "type": "boolean",
                "default": False,
                "description": "Import the good rows even if some have errors.",
            },
        },
        "additionalProperties": False,
        "$defs": {"unit": unit},
    }


def sample_json() -> dict[str, Any]:
    units: list[dict[str, Any]] = [{k: v for k, v in row.items() if v} for row in SAMPLE_ROWS[:2]]
    units[0]["forks"] = ["1.75 x 4 x 48 STD", "1.75 x 4 x 48 STD"]
    units[0]["attachment_1_hose_reel"] = True
    return {"reference": "scanner-2026-10-05-01", "dry_run": True, "units": units}


def markdown() -> str:
    sections: dict[str, list[Column]] = {}
    for col in COLUMNS:
        sections.setdefault(col.section, []).append(col)
    lines = [
        "# Import format: unit cards",
        "",
        "<!-- Generated by `python manage.py write_import_docs` from backend/apps/imports/columns.py. Do not edit by hand. -->",
        "",
        'Use this to load the paper "Eagle 1-84" unit cards (or any list of units) into the DMS.',
        "",
        "Files:",
        "",
        "- [unit-import-template.csv](import/unit-import-template.csv): the empty template (header row only).",
        "- [unit-import-sample.csv](import/unit-import-sample.csv): the same with three filled-in example cards.",
        "- [unit-import.schema.json](import/unit-import.schema.json): JSON Schema for the import API.",
        "- [unit-import-sample.json](import/unit-import-sample.json): an example API request.",
        "",
        "The template and sample can also be downloaded in the app: **Imports → Download template**.",
        "",
        "## Filling in the spreadsheet",
        "",
        "1. Open the template in Excel or Google Sheets. Keep the first row (the column names) as it is.",
        "2. Add **one row per unit card**. Type values as they're written on the card. Leave anything you can't read blank.",
        "3. Every row needs a `unit_serial` (or, for a unit without one, a `stock_number`). That's how the DMS recognises a unit, so importing the same card twice never makes a duplicate.",
        "4. Before typing serial numbers, format the serial columns as **Text**, or Excel may change them (for example `1234E5` or long numbers).",
        "5. If you scanned the cards, put each scan's file name in `source_image_filename` (for example `card-0412.jpg`). Upload the scans together with the CSV and each one is attached to its unit.",
        "6. Save as **CSV UTF-8 (Comma delimited)**. In Google Sheets: File → Download → Comma-separated values.",
        "",
        "Then in the DMS: **Imports → New import**, choose the CSV (and the scans), and check the preview. Nothing changes until you press **Import**.",
        "",
        "## What happens on import",
        "",
        '- **New units** are added. The customer is matched by name (ignoring case, punctuation and endings like "Co." or "Inc"). If there\'s no match, a new customer is added.',
        '- **Units already in the DMS** (same serial) are updated with the card\'s values, unless you choose "Leave existing units alone". Blank cells never erase anything.',
        "- **Importing the same file again** changes nothing.",
        "- Values that can't be read as a number or date (for example `5 ton` in `capacity_lbs`) are kept, exactly as written, in the unit's notes, and the unit is flagged **Needs review**.",
        "- Every unit added with a warning is flagged **Needs review**. Find them under *Units → filter: Only units that need review*.",
        "- The hour meter becomes a dated reading (the card date, or the import date).",
        "- The owner of a unit already in the DMS is never changed by an import. Use **Change owner** on the unit page.",
        "- **Undo**: on the import's page, *Undo this import* reverses the whole batch. Units that someone edited after the import are left alone and listed.",
        "",
        "## Rules",
        "",
        "- Up to 5,000 rows and 10 MB per CSV file; up to 2,000 scans (25 MB each) per import.",
        "- Dates: `2024-03-12` or `3/12/2024`.",
        "- Yes/no columns: `yes` / `no` (also `y`, `true`, `x`, `1`).",
        "- Prices are only imported for admin and sales users.",
        f"- Attachments: up to {MAX_ATTACHMENTS} per unit (`attachment_1_…` to `attachment_{MAX_ATTACHMENTS}_…`).",
        "- Several forks: separate with `;`. `1.75 x 4 x 48 STD; 1.75 x 4 x 48 STD` is a pair.",
        "- Column names are not case sensitive. Unknown columns are ignored (and listed in the preview).",
        "",
        "## Columns",
        "",
    ]
    for section, cols in sections.items():
        lines += [f"### {section}", "", "| Column | Type | Description |", "|---|---|---|"]
        for col in cols:
            kind = {
                "text": f"text{f' (max {col.max_length})' if col.max_length else ''}",
                "int": "whole number",
                "decimal": "number",
                "hours": "number",
                "money": "dollars",
                "date": "date",
                "bool": "yes / no",
                "forks": "text, `;` between sets",
                "choice": "one of: " + ", ".join(f"`{v}`" for v in dict.fromkeys(col.choices)),
            }[col.kind]
            lines.append(f"| `{col.name}` | {kind} | {col.help} |")
        lines.append("")
    lines += [
        "## Import API (for the scanning app)",
        "",
        "The same data can be sent as JSON. An admin creates an API key under **Admin → API keys** (it's shown once). Imports made with a key are recorded as the admin who created it.",
        "",
        "```",
        f"POST {API_PATH}",
        "Authorization: Api-Key mmh_…",
        "Content-Type: application/json",
        "```",
        "",
        "The body follows [unit-import.schema.json](import/unit-import.schema.json); see [unit-import-sample.json](import/unit-import-sample.json). Each unit uses the CSV column names as keys. `forks` and `source_image_filename` may be lists.",
        "",
        "| Field | Meaning |",
        "|---|---|",
        "| `units` | 1 to 1,000 unit cards. |",
        "| `dry_run` | `true`: check only and return the report (status 200). Nothing changes. |",
        "| `on_existing` | `update` (default) or `skip` units that are already in the DMS. |",
        "| `skip_invalid` | `true`: import the good rows even if others have errors. Otherwise any error stops the whole batch (status 422) and nothing changes. |",
        "| `reference` | Your own id for the batch, shown in the app. |",
        "",
        "Responses:",
        "",
        "- `201` imported: the batch with a result per row (`created`, `updated`, `unchanged`, `skipped`, `failed`).",
        "- `202` accepted: a big batch is importing in the background. Check `GET /api/v1/import/v1/batches/{id}`.",
        "- `200` dry run report. `422` rows have errors (see each row's `errors`). `401` bad or revoked key. `429` too many requests (limit: 30 per minute per key).",
        "",
        "To include scanned cards: send the units with `dry_run: true`. The batch stays open as a draft. Upload each scan to `POST /api/v1/import/v1/batches/{id}/files` (multipart, field `file`), then import it with `POST /api/v1/import/v1/batches/{id}/apply` (body: `on_existing`, `skip_invalid`).",
        "",
    ]
    return "\n".join(lines)


def json_dump(data: Any) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"
