# Generated by Django 5.2.17 on 2026-10-05 14:45

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.units.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("make", models.CharField(blank=True, default="", max_length=60)),
                ("model", models.CharField(blank=True, default="", max_length=80)),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "serial_normalized",
                    models.CharField(blank=True, default="", editable=False, max_length=80),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "stock_number",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("card_date", models.DateField(blank=True, null=True)),
                (
                    "card_customer_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("mechanic", models.CharField(blank=True, default="", max_length=100)),
                (
                    "work_order_number",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "New"), ("used", "Used")],
                        default="used",
                        max_length=10,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lpg", "LPG"),
                            ("gasoline", "Gasoline"),
                            ("diesel", "Diesel"),
                            ("dual", "Dual fuel (LPG/gas)"),
                            ("electric", "Electric"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("capacity_lbs", models.PositiveIntegerField(blank=True, null=True)),
                ("mast_make", models.CharField(blank=True, default="", max_length=60)),
                ("mast_type", models.CharField(blank=True, default="", max_length=60)),
                ("mast_size", models.CharField(blank=True, default="", max_length=60)),
                (
                    "mast_lift_height_in",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum fork height, inches", null=True
                    ),
                ),
                (
                    "mast_lowered_height_in",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "lift_cylinder_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("carriage", models.CharField(blank=True, default="", max_length=100)),
                (
                    "backrest_height",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "backrest_width",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "tilt_forward_deg",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
                ),
                (
                    "tilt_back_deg",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
                ),
                (
                    "tilt_reference",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("tire_type", models.CharField(blank=True, default="", max_length=40)),
                (
                    "tire_drive_size",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "tire_steer_size",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "tire_notes",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "battery_make",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "battery_model",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "battery_serial",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "battery_volts",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "battery_amp_hours",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "battery_size",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "battery_weight_lbs",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "charger_make",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "charger_model",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "charger_serial",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("special_equipment", models.TextField(blank=True, default="")),
                ("field_modifications", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "stock_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("on_hold", "On hold"),
                            ("in_prep", "In prep"),
                            ("sold", "Sold"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "asking_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("needs_review", models.BooleanField(default=False)),
                (
                    "review_note",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["make", "model", "serial_number"],
            },
        ),
        migrations.CreateModel(
            name="OwnershipRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "owner_kind",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("dealer", "Maine Material Handling stock"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ownerships",
                        to="customers.customer",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ownerships",
                        to="units.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HourMeterReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "reading_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=9,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("card", "Unit card"),
                            ("service", "Service"),
                            ("sale", "Sale / trade-in"),
                            ("manual", "Entered by hand"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hour_readings",
                        to="units.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["-reading_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnitAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("type", models.CharField(blank=True, default="", max_length=80)),
                ("model", models.CharField(blank=True, default="", max_length=80)),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("date_code", models.CharField(blank=True, default="", max_length=40)),
                ("hose_reel", models.BooleanField(default=False)),
                ("internal_hose", models.BooleanField(default=False)),
                (
                    "reel_number",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[("LH", "Left (LH)"), ("RH", "Right (RH)")],
                        default="",
                        max_length=2,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="units.unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnitComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("engine", "Engine"),
                            ("alternator", "Generator / alternator"),
                            ("controller", "Electrical controller"),
                            ("ignition", "Ignition system"),
                            ("fuel_system", "Fuel system"),
                            ("hydraulic_pump", "Hydraulic pump"),
                            ("control_valve", "Control valve"),
                            ("transmission", "Transmission"),
                        ],
                        max_length=20,
                    ),
                ),
                ("make", models.CharField(blank=True, default="", max_length=60)),
                ("model", models.CharField(blank=True, default="", max_length=80)),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "spools",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("2SP", "2 spool"),
                            ("3SP", "3 spool"),
                            ("4SP", "4 spool"),
                        ],
                        default="",
                        max_length=3,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components",
                        to="units.unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnitFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("scanned_card", "Scanned unit card"),
                            ("document", "Document"),
                        ],
                        default="photo",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(max_length=300, upload_to=apps.units.models.unit_file_path),
                ),
                (
                    "thumbnail",
                    models.FileField(
                        blank=True,
                        default="",
                        max_length=300,
                        upload_to=apps.units.models.unit_file_path,
                    ),
                ),
                (
                    "original_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("caption", models.CharField(blank=True, default="", max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files",
                        to="units.unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnitFork",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("dimensions", models.CharField(max_length=80)),
                ("quantity", models.PositiveSmallIntegerField(default=2)),
                (
                    "thickness_in",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "width_in",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "length_in",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forks",
                        to="units.unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["stock_status", "condition"], name="unit_stock_idx"),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["make", "model"], name="unit_make_model_idx"),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                condition=models.Q(("needs_review", True)),
                fields=["needs_review"],
                name="unit_review_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("serial_normalized", ""), _negated=True),
                fields=("serial_normalized",),
                name="unit_serial_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    models.Q(("stock_number", ""), _negated=True),
                ),
                fields=("stock_number",),
                name="unit_stock_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.CheckConstraint(
                condition=models.Q(("condition__in", ["new", "used"])),
                name="unit_condition_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "stock_status__in",
                        ["", "available", "on_hold", "in_prep", "sold"],
                    )
                ),
                name="unit_stock_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "fuel_type__in",
                        ["", "lpg", "gasoline", "diesel", "dual", "electric", "other"],
                    )
                ),
                name="unit_fuel_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cost__isnull", True), ("cost__gte", 0), _connector="OR"),
                    models.Q(
                        ("asking_price__isnull", True),
                        ("asking_price__gte", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("sale_price__isnull", True),
                        ("sale_price__gte", 0),
                        _connector="OR",
                    ),
                ),
                name="unit_money_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("year__isnull", True),
                    models.Q(("year__gte", 1940), ("year__lte", 2100)),
                    _connector="OR",
                ),
                name="unit_year_sane",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("serial_number", ""), _negated=True),
                    models.Q(("model", ""), _negated=True),
                    models.Q(("stock_number", ""), _negated=True),
                    _connector="OR",
                ),
                name="unit_identifiable",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownershiprecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("customer__isnull", False), ("owner_kind", "customer")),
                    models.Q(("customer__isnull", True), ("owner_kind", "dealer")),
                    _connector="OR",
                ),
                name="ownership_owner_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownershiprecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="ownership_dates_in_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownershiprecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("end_date__isnull", True)),
                fields=("unit",),
                name="ownership_one_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="hourmeterreading",
            constraint=models.CheckConstraint(
                condition=models.Q(("hours__gte", 0)), name="hours_not_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="hourmeterreading",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["card", "service", "sale", "manual"])),
                name="hours_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitattachment",
            constraint=models.CheckConstraint(
                condition=models.Q(("side__in", ["", "LH", "RH"])),
                name="attachment_side_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitattachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("manufacturer", ""), _negated=True),
                    models.Q(("type", ""), _negated=True),
                    models.Q(("model", ""), _negated=True),
                    _connector="OR",
                ),
                name="attachment_described",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitcomponent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("unit", "kind"),
                name="component_one_per_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "engine",
                            "alternator",
                            "controller",
                            "ignition",
                            "fuel_system",
                            "hydraulic_pump",
                            "control_valve",
                            "transmission",
                        ],
                    )
                ),
                name="component_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("spools", ""),
                    models.Q(("kind", "control_valve"), ("spools__in", ["2SP", "3SP", "4SP"])),
                    _connector="OR",
                ),
                name="component_spools_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitfile",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["photo", "scanned_card", "document"])),
                name="unitfile_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitfile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_primary", True)),
                fields=("unit",),
                name="unitfile_one_primary",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitfork",
            constraint=models.CheckConstraint(
                condition=models.Q(("dimensions", ""), _negated=True),
                name="fork_dimensions_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitfork",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1), ("quantity__lte", 8)),
                name="fork_quantity_sane",
            ),
        ),
    ]
