# Phase 9: parts catalog. # Generated by Django 5.2.17 on 2026-10-05 23:32

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("code", models.CharField(max_length=30)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("part_number", models.CharField(max_length=60)),
                ("number_normalized", models.CharField(editable=False, max_length=60)),
                (
                    "manufacturer_normalized",
                    models.CharField(blank=True, default="", editable=False, max_length=60),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("filters", "Filters"),
                            ("engine", "Engine and fuel"),
                            ("hydraulics", "Hydraulics"),
                            ("brakes", "Brakes"),
                            ("electrical", "Electrical"),
                            ("mast", "Mast, chains and forks"),
                            ("tires", "Tires and wheels"),
                            ("drivetrain", "Transmission and drivetrain"),
                            ("steering", "Steering"),
                            ("safety", "Lights and safety"),
                            ("attachments", "Attachments"),
                            ("fluids", "Fluids and shop supplies"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("each", "Each"),
                            ("pair", "Pair"),
                            ("set", "Set"),
                            ("kit", "Kit"),
                            ("box", "Box"),
                            ("foot", "Foot"),
                            ("quart", "Quart"),
                            ("gallon", "Gallon"),
                        ],
                        default="each",
                        max_length=10,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "list_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "reorder_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("vendor", models.CharField(blank=True, default="", max_length=100)),
                (
                    "vendor_part_number",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("fits", models.CharField(blank=True, default="", max_length=300)),
                ("notes", models.TextField(blank=True, default="")),
                ("superseded_on", models.DateField(blank=True, null=True)),
                (
                    "bin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parts",
                        to="parts.bin",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supersedes",
                        to="parts.part",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["manufacturer", "part_number"],
            },
        ),
        migrations.CreateModel(
            name="CrossReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("part_number", models.CharField(max_length=60)),
                ("number_normalized", models.CharField(editable=False, max_length=60)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cross_references",
                        to="parts.part",
                    ),
                ),
            ],
            options={
                "ordering": ["manufacturer", "part_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="bin",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="bin_code_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="bin",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("code"),
                condition=models.Q(("deleted_at__isnull", True)),
                name="bin_code_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(fields=["number_normalized"], name="part_number_idx"),
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(fields=["category"], name="part_category_idx"),
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.CheckConstraint(
                condition=models.Q(("number_normalized", ""), _negated=True),
                name="part_number_given",
            ),
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.CheckConstraint(
                condition=models.Q(("description", ""), _negated=True),
                name="part_described",
            ),
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.UniqueConstraint(
                fields=("manufacturer_normalized", "number_normalized"),
                name="part_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "category__in",
                        [
                            "filters",
                            "engine",
                            "hydraulics",
                            "brakes",
                            "electrical",
                            "mast",
                            "tires",
                            "drivetrain",
                            "steering",
                            "safety",
                            "attachments",
                            "fluids",
                            "other",
                        ],
                    )
                ),
                name="part_category_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "unit_of_measure__in",
                        [
                            "each",
                            "pair",
                            "set",
                            "kit",
                            "box",
                            "foot",
                            "quart",
                            "gallon",
                        ],
                    )
                ),
                name="part_unit_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cost__isnull", True), ("cost__gte", 0), _connector="OR"),
                    models.Q(
                        ("list_price__isnull", True),
                        ("list_price__gte", 0),
                        _connector="OR",
                    ),
                ),
                name="part_money_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("reorder_point__isnull", True),
                        ("reorder_point__gte", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("reorder_quantity__isnull", True),
                        ("reorder_quantity__gt", 0),
                        _connector="OR",
                    ),
                ),
                name="part_reorder_sane",
            ),
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("superseded_by__isnull", True),
                    models.Q(("superseded_by", models.F("id")), _negated=True),
                    _connector="OR",
                ),
                name="part_not_superseded_by_itself",
            ),
        ),
        migrations.AddIndex(
            model_name="crossreference",
            index=models.Index(fields=["number_normalized"], name="cross_ref_number_idx"),
        ),
        migrations.AddConstraint(
            model_name="crossreference",
            constraint=models.CheckConstraint(
                condition=models.Q(("number_normalized", ""), _negated=True),
                name="cross_ref_number_given",
            ),
        ),
        migrations.AddConstraint(
            model_name="crossreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("part", "number_normalized"),
                name="cross_ref_once",
            ),
        ),
    ]
