# Generated by Django 5.2.17 on 2026-10-06 00:05

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parts", "0003_feature_flag"),
        ("service", "0005_plan_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCheck",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("parts_checked", models.PositiveIntegerField(default=0)),
                ("drift", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PartStock",
            fields=[
                (
                    "part",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="stock",
                        serialize=False,
                        to="parts.part",
                    ),
                ),
                (
                    "on_hand",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("on_hand__gte", 0)),
                        name="stock_not_negative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("opening", "Opening count"),
                            ("receive", "Received"),
                            ("issue", "Used on a work order"),
                            ("return", "Returned from a work order"),
                            ("adjust", "Count adjustment"),
                            ("reversal", "Reversal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=60)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="parts.part",
                    ),
                ),
                (
                    "reverses",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="parts.stockmovement",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="part_movements",
                        to="service.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["part", "-occurred_at"], name="movement_part_idx"),
                    models.Index(fields=["work_order"], name="movement_work_order_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity", 0), _negated=True),
                        name="movement_not_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "kind__in",
                                [
                                    "opening",
                                    "receive",
                                    "issue",
                                    "return",
                                    "adjust",
                                    "reversal",
                                ],
                            )
                        ),
                        name="movement_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind__in", ["opening", "receive"]),
                                ("quantity__gt", 0),
                            ),
                            models.Q(
                                ("kind", "issue"),
                                ("quantity__lt", 0),
                                ("work_order__isnull", False),
                            ),
                            models.Q(
                                ("kind", "return"),
                                ("quantity__gt", 0),
                                ("work_order__isnull", False),
                            ),
                            ("kind", "adjust"),
                            models.Q(("kind", "reversal"), ("reverses__isnull", False)),
                            _connector="OR",
                        ),
                        name="movement_kind_fits",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("work_order__isnull", True),
                            ("kind__in", ["issue", "return", "reversal"]),
                            _connector="OR",
                        ),
                        name="movement_work_order_only_when_used",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("balance_after__gte", 0)),
                        name="movement_balance_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("unit_cost__isnull", True),
                                ("unit_cost__gte", 0),
                                _connector="OR",
                            ),
                            models.Q(
                                ("unit_price__isnull", True),
                                ("unit_price__gte", 0),
                                _connector="OR",
                            ),
                        ),
                        name="movement_money_not_negative",
                    ),
                ],
            },
        ),
    ]
