# Phase 8: quotes and sales. Generated by Django 5.2.17 on 2026-10-05 22:41

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.sales.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0002_db_guards"),
        ("units", "0005_feature_flag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SEQUENCE IF NOT EXISTS sales_quote_number_seq START 30001",
            "DROP SEQUENCE IF EXISTS sales_quote_number_seq",
        ),
        migrations.RunSQL(
            "CREATE SEQUENCE IF NOT EXISTS sales_sale_number_seq START 40001",
            "DROP SEQUENCE IF EXISTS sales_sale_number_seq",
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                            ("sold", "Sold"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "quote_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("attention", models.CharField(blank=True, default="", max_length=120)),
                (
                    "customer_po",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=apps.sales.models.default_tax_rate,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(25),
                        ],
                    ),
                ),
                ("tax_exempt", models.BooleanField(default=False)),
                (
                    "tax_exempt_number",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "terms",
                    models.TextField(
                        blank=True,
                        default="Prices in US dollars. Quote valid until the date shown. Units are subject to prior sale. Trade-in allowances assume the trade-in is in the condition we inspected.",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="customers.customer",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "salesperson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-quote_date", "-number"],
            },
        ),
        migrations.CreateModel(
            name="QuoteLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("unit", "Unit"),
                            ("attachment", "Attachment or option"),
                            ("delivery", "Delivery"),
                            ("service", "Service or warranty"),
                            ("other", "Other"),
                            ("discount", "Discount"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=Decimal("1"), max_digits=8),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("taxable", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="sales.quote",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_lines",
                        to="units.unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Completed"), ("voided", "Voided")],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "sale_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "trade_allowance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("trade_payoff", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("tax_rate", models.DecimalField(decimal_places=3, max_digits=5)),
                ("tax", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="customers.customer",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="sales.quote",
                    ),
                ),
                (
                    "salesperson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sale_date", "-number"],
            },
        ),
        migrations.CreateModel(
            name="SaleUnitChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("sold", "Sold"), ("trade_in", "Trade-in")],
                        max_length=10,
                    ),
                ),
                ("created_unit", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ownership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_change",
                        to="units.ownershiprecord",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unit_changes",
                        to="sales.sale",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("make", models.CharField(blank=True, default="", max_length=60)),
                ("model", models.CharField(blank=True, default="", max_length=80)),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=9,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "payoff",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("payoff_to", models.CharField(blank=True, default="", max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_ins",
                        to="sales.quote",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_ins",
                        to="units.unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["status", "-quote_date"], name="quote_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["draft", "sent", "accepted", "declined", "cancelled", "sold"],
                    )
                ),
                name="quote_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_until__gte", models.F("quote_date")),
                    _connector="OR",
                ),
                name="quote_valid_after_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_rate__gte", 0), ("tax_rate__lte", 25)),
                name="quote_tax_rate_sane",
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "unit",
                            "attachment",
                            "delivery",
                            "service",
                            "other",
                            "discount",
                        ],
                    )
                ),
                name="quote_line_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="quote_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "unit"), ("quantity", 1), ("unit__isnull", False)),
                    models.Q(
                        models.Q(("kind", "unit"), _negated=True),
                        ("unit__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="quote_line_unit_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "discount"), ("unit_price__lte", 0)),
                    models.Q(
                        models.Q(("kind", "discount"), _negated=True),
                        ("unit_price__gte", 0),
                    ),
                    _connector="OR",
                ),
                name="quote_line_price_sign",
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "unit"), _negated=True),
                    ("unit__isnull", False),
                    models.Q(("description", ""), _negated=True),
                    _connector="OR",
                ),
                name="quote_line_described",
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("unit__isnull", False)),
                fields=("quote", "unit"),
                name="quote_line_unit_once",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["completed", "voided"])),
                name="sale_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "voided"), _negated=True),
                    models.Q(
                        ("voided_at__isnull", False),
                        models.Q(("void_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="sale_voided_has_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("status", "completed")),
                fields=("quote",),
                name="sale_one_completed_per_quote",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tax__gte", 0),
                    ("trade_allowance__gte", 0),
                    ("trade_payoff__gte", 0),
                    ("taxable_amount__gte", 0),
                ),
                name="sale_money_sane",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleunitchange",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["sold", "trade_in"])),
                name="sale_change_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="tradein",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unit__isnull", False),
                    models.Q(("serial_number", ""), _negated=True),
                    models.Q(("model", ""), _negated=True),
                    _connector="OR",
                ),
                name="trade_in_identified",
            ),
        ),
        migrations.AddConstraint(
            model_name="tradein",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allowance__gte", 0),
                    models.Q(("payoff__isnull", True), ("payoff__gte", 0), _connector="OR"),
                ),
                name="trade_in_money_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="tradein",
            constraint=models.CheckConstraint(
                condition=models.Q(("hours__isnull", True), ("hours__gte", 0), _connector="OR"),
                name="trade_in_hours_sane",
            ),
        ),
        migrations.AddConstraint(
            model_name="tradein",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("unit__isnull", False)),
                fields=("quote", "unit"),
                name="trade_in_unit_once",
            ),
        ),
    ]
