# Generated by Django 5.2.17 on 2026-10-05 16:19

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.imports.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("units", "0003_feature_flag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("prefix", models.CharField(max_length=12, unique=True)),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("csv", "CSV upload"), ("api", "Import API")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Checked, not imported yet"),
                            ("queued", "Waiting to import"),
                            ("importing", "Importing"),
                            ("imported", "Imported"),
                            ("failed", "Import failed"),
                            ("undoing", "Undoing"),
                            ("undone", "Undone"),
                            ("discarded", "Discarded"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("reference", models.CharField(blank=True, default="", max_length=100)),
                (
                    "original",
                    models.FileField(
                        blank=True,
                        max_length=300,
                        upload_to=apps.imports.models.batch_file_path,
                    ),
                ),
                (
                    "on_existing",
                    models.CharField(
                        choices=[
                            ("update", "Fill in and update the existing unit"),
                            ("skip", "Leave the existing unit alone"),
                        ],
                        default="update",
                        max_length=10,
                    ),
                ),
                ("skip_invalid", models.BooleanField(default=False)),
                ("file_messages", models.JSONField(blank=True, default=list)),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="imports.apikey",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "undone_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(max_length=300, upload_to=apps.imports.models.scan_file_path),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files",
                        to="imports.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["original_name"],
            },
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("raw", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Ready"),
                            ("warning", "Ready, with warnings"),
                            ("error", "Has errors"),
                        ],
                        default="ok",
                        max_length=10,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("create", "Add a new unit"),
                            ("update", "Update an existing unit"),
                            ("unchanged", "Already up to date"),
                            ("skip", "Skip"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("errors", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("changes", models.JSONField(blank=True, default=list)),
                ("serial", models.CharField(blank=True, default="", max_length=80)),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not imported"),
                            ("created", "Added"),
                            ("updated", "Updated"),
                            ("unchanged", "No changes needed"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("undo", models.JSONField(blank=True, default=dict)),
                (
                    "undo_result",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rows",
                        to="imports.importbatch",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="units.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="apikey",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="api_key_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["csv", "api"])),
                name="batch_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "draft",
                            "queued",
                            "importing",
                            "imported",
                            "failed",
                            "undoing",
                            "undone",
                            "discarded",
                        ],
                    )
                ),
                name="batch_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("on_existing__in", ["update", "skip"])),
                name="batch_on_existing_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importfile",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("original_name"),
                models.F("batch"),
                name="import_file_name_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=models.Index(fields=["batch", "status"], name="import_row_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "row_number"), name="import_row_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["ok", "warning", "error"])),
                name="import_row_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.CheckConstraint(
                condition=models.Q(("plan__in", ["", "create", "update", "unchanged", "skip"])),
                name="import_row_plan_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "result__in",
                        ["", "created", "updated", "unchanged", "skipped", "failed"],
                    )
                ),
                name="import_row_result_valid",
            ),
        ),
    ]
